---
- hosts: localhost
  user: moose
  connection: local

  vars:
    dock_tile_size: 45
    dock_large_tile_size: 50
    dock_auto_hide: true
    dotfiles_github_repo: moos3/dotfiles.git
    username: moose
    gnupg_github_repo: moos3/gnupg.git

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.homebrew
    - dotfiles
    - macosx-setup

  post_tasks:
    - name: Remove default .gnupg
      shell: "{{ item }}"
      with_items:
        - rm -rf /Users/{{ username }}/.gnupg
    - name: Clone dotfiles
      git: repo=https://{{ tokens.github }}@github.com/{{ gnupg_github_repo }} dest=/Users/{{ username }}/.gnupg recursive=yes update=no
