---
- hosts: localhost
  user: moose
  connection: local
  
  var_prompt:
    - name: "githubuser"
      prompt: "Enter your github username"
      private: no
    - name: "githubpassword"
      prompt: "Enter your github password"
      private: yes

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.homebrew
    - dotfiles
    - macosx-setup
