---
- hosts: localhost
  user: moose
  connection: local

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.homebrew
    - dotfiles
    - macosx-setup

  vars_prompt:
    - name: "githubtoken"
      prompt: "Enter your github peronsal access token"
      private: no
